[workspace]

members = [
  "base",
  "daemon",
  "scanner",
]

default-members = ["daemon"]

[patch.crates-io]
pulldown-cmark = { git = 'https://github.com/gozala/pulldown-cmark', branch = 'link-id' } 
